### PR TITLE
Added Cargo support to Docker image.

### PR DESCRIPTION
**Pull request by marvin-hansen**
## Checklist

- [x] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?

https://github.com/phylum-dev/phylum-analyze-pr-action/issues/29

### CODE REVIEW

**Comment by maxrake** [comment]
Sorry for the delay in getting an initial response out. Phylum internal discussions have resulted in an increased prioritization for adding [lockfile generation](https://docs.phylum.io/docs/lockfile_generation) support to the `phylum-ci` Docker image and therefore most of the integrations. A research spike is currently underway to determine the best way to do this as there are a number of considerations and questions to answer:

* Should all required tools be installed in the same image, regardless of size?
  * If so, should a "slim" version be offered...to represent the current behavior where only lockfiles are supported
  * If not, which tools should go together?
* If multiple images are offered, how will the [GitHub Action](https://github.com/phylum-dev/phylum-analyze-pr-action) be updated to account for the different options?
  * Provide a new input to select the image?
  * Default to the new larger image and don't allow for changing?
* Minimizing image download times and overall integration run times are important
* What options are available to minimize the image size?
* What is the minimum required to get each required tool functional for the purposes needed by Phylum
* It might be necessary to [replace lockfile detection with `phylum status`](https://github.com/phylum-dev/phylum-ci/issues/244) commands before rolling out this feature
* The documentation for all integrations will need to be updated in a coordinated manner
* Testing for support is important

Then, a holistic solution will be implemented to bring full support to the broadest range of manifest files. 

For those reasons, this PR will be closed as it does not take into account the larger picture. The ideas presented here have already been useful while researching the various ways `cargo` can be installed and how it interacts with the other required tools. We thank you for that and for your patience as this feature is implemented and rolled out.

**Comment by marvin-hansen** [comment]
Thank you,

I understand that there is definitely a need to cover all supported
integrations. Just a few thoughts:

1) Definitely one image. Mixed mono repos need different tools.

2) Container can be done multistage for better maintenance.

3) Image size and download time is actually secondary for me. But I suggest
running a community poll to get some feedback.


If you need a beta tester, let me know.

Thank you for putting this together.

**Comment by maxrake** [comment]
> If you need a beta tester, let me know.

@marvin-hansen, work on the holistic solution is underway, with a new image available for testing now if you like. It is not part of a `phylum-dev/phylum-ci` release yet since there are still a few issues left to complete:

* phylum-dev/phylum-ci#317
* phylum-dev/phylum-ci#244
* phylum-dev/phylum-analyze-pr-action#30
* phylum-dev/documentation#61

However, tags for the images created with the updated/new dockerfiles in the [PR that added lockfile generation support](https://github.com/phylum-dev/phylum-ci/pull/318) can be found [on Docker Hub for my personal account](https://hub.docker.com/r/maxrake/phylum-ci/tags). The `manifest_support` tag is built with the new `Dockerfile`.

**Comment by marvin-hansen** [comment]
@maxrake 

Do you have a forked GitHub action with the new test container which I can put in my CI for testing?

**Comment by maxrake** [comment]
> Do you have a forked GitHub action with the new test container which I can put in my CI for testing?

Ah...yeah, that would help...sorry. I just created a `manifest_support` branch there for testing. It can be used by changing the action line in workflows to:

```
uses: phylum-dev/phylum-analyze-pr-action@manifest_support
```

The full solution will be rolled out and better supported with the ability to select between images in the GitHub action. Still working on all of that...targeting this week for completion.

**Comment by marvin-hansen** [comment]
@maxrake 

It's running now but I see a call to update in my logs

gnoring empty PHYLUM_API_KEY
---------------- Update Available ----------------

A new version of the Phylum CLI is available. Run

	phylum update

to update to the latest version!

--------------------------------------------------

I think the docker image needs a CI trigger to build a new image whenever a new version comes out;

**Comment by marvin-hansen** [comment]
@maxrake The run consistently fails with the error

⚠️  User is not currently authenticated, please login with `phylum auth login`
A Phylum API key is required to continue.


I've two repo secrets:

PHYLUM_TOKEN
and
PHYLUM_API_KEY

both containing a newly generated API key. I think the first (PHYLUM_TOKEN) was from the official docs. When that run failed, I've looked at the actual command executed in Docker and saw that somehow the Env variable is named PHYLUM_API_KEY so I created one and it failed again.

Full log:
https://github.com/deepcausality-rs/deep_causality/actions/runs/6477944982/job/17589064230

Config in use:
https://github.com/deepcausality-rs/deep_causality/actions/runs/6477944982/workflow

**Comment by kylewillmon** [comment]
@marvin-hansen The workflow run you linked was triggered by deepcausality-rs/deep_causality#111 which originates from a fork of the repository.

GitHub [intentionally disables][1] secrets in that situation. Here's the excerpt from the docs:

> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

[1]: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

Without the secret, the environment variable is empty as can be seen in the logs:

```
⚠️  Ignoring empty PHYLUM_API_KEY
```

**Comment by maxrake** [comment]
@marvin-hansen

> I think the docker image needs a CI trigger to build a new image whenever a new version comes out;

Agreed...and it does so already...but only for the official Phylum images (`phylumio/phylum-ci` on Docker Hub and `ghcr.io/phylum-dev/phylum-ci` on GitHub Container Registry). We just [released a new version of the Phylum CLI](https://github.com/phylum-dev/cli/releases/tag/v5.7.2) yesterday...to include fixes to issues you first pointed out (thanks!) like lockfile generation for workspaces.

There is a coordinated release of the full manifest support coming this week, at which point all the documentation, images, and `phylum-ci` tool will be current. It might just be best to wait for that before continuing, but I went ahead and pushed a new build of the `maxrake/phylum-ci:manifest_support` image to Docker Hub anyway. It includes the latest Phylum CLI.

**Comment by marvin-hansen** [comment]
@maxrake 

Ok, this is a very buggy release... 

When I run the GH Action on push, I get a weirdo error stating rustup could not chose a version, because of, well, [you have to read this in the log. ](https://github.com/deepcausality-rs/temp/actions/runs/6506262827/job/17671479188)

Here is the config file: https://github.com/deepcausality-rs/temp/actions/runs/6506262827/workflow

 All my project repos have branch protection on by default meaning nearly all my GH actions run on PR to flag problematic PR's before merge. After all, anyone could contribute so I already run multiple security and sanity checks on every PR. Practically, phylum  needs to run on every PR to be useful. The alternative is on push after merge, but this means if phylum flags a dependency, I have to manually revert git, which is clearly undesirable by any standard.

I loosely remember that I bumped into the API key / fork-PR issue a while ago. There are roughly two solutions.

1) Use an API that doesn't need an API key. Rust security team already provided an API key free access for a while so the rust security analyzer runs without requiring a secret API key. I believe they do have abuse protection that blocks IP addresses that somehow exceed reasonable usage.

2) labelled pull_request_target

The idea is to label incoming PR's with a pre-defined label "request-security-check" and once that label is assigned, a pull_request_target event is triggered that has access to keys in the target repo. pull_request does not have access to secrets whereas pull_request_target does because it runs in the context of the target repo, as[ per the documentation.](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) 

That said, configuration is really tricky and I was not able to make it work yet. The idea so far is to auto-comment on any newly opened PR from a fork to add a label to request security check (that works) and once the label is added, trigger an event (that works, too) and once the event is detected, run phylum which fails stating the triggering action must be pull_request.

log
https://github.com/deepcausality-rs/temp/actions/runs/6506290056/job/17671553997
config
https://github.com/deepcausality-rs/temp/actions/runs/6506290056/workflow

Is the phylum GH action somehow limited to pull_request so that it does not allow for pull_request_target?

Regardless, considering how hard it is to make phylum work, I created a test repo to experiment around and will check there every once in a while to see how it goes. 

In the meantime, I suggest more internal testing on random Rust repos i.e. tokio, clap etc. because there is no way this can be used without major bug fixing.

**Comment by maxrake** [comment]
@marvin-hansen, thank you for your feedback and links to configs. It has helped to troubleshoot.

> When I run the GH Action on push, I get a weirdo error stating rustup could not chose a version, because of, well, [you have to read this in the log. ](https://github.com/deepcausality-rs/temp/actions/runs/6506262827/job/17671479188)

This one stumped me for a bit since I couldn't recreate the error locally, but then I was able to do so by running the action on a Rust manifest file (I had been using Python to that point) and within the GitHub Actions environment (which turns out to have unique actions for Docker container actions/jobs).

However, this issue was ultimately identified and fixed here: https://github.com/phylum-dev/phylum-ci/pull/329. The `maxrake/phylum-ci:manifest_support` image was updated to include the changes but should not be used much longer since the official Phylum Docker images were just updated with the initial manifest support release. This is _initial_ support because there are still a few known limitations...some of which you outline here.

> 1. Use an API that doesn't need an API key. Rust security team already provided an API key free access for a while so the rust security analyzer runs without requiring a secret API key. I believe they do have abuse protection that blocks IP addresses that somehow exceed reasonable usage.

I'll bring this up with the team, but I suspect there is/was a reason for the API key, even for the free Community Edition of Phylum.

> Is the phylum GH action somehow limited to pull_request so that it does not allow for pull_request_target?

Yes, [that is a current pre-requisite](https://github.com/phylum-dev/phylum-ci/blob/main/src/phylum/ci/ci_github.py#L87-L92). A [new issue has been created](https://github.com/phylum-dev/phylum-ci/issues/331) to expand the events supported by this action.

> Regardless, considering how hard it is to make phylum work, I created a test repo to experiment around and will check there every once in a while to see how it goes.

Sounds good...we appreciate any feedback! One suggestion for now is to switch the Docker image back over to the official Phylum account. This can be done by changing the action from `phylum-dev/phylum-analyze-pr-action@manifest_support` to `phylum-dev/phylum-analyze-pr-action@v2` (or whatever tag/sha you are comfortable with). That `manifest_support` branch will be removed in the next day or so.

> In the meantime, I suggest more internal testing on random Rust repos i.e. tokio, clap etc. because there is no way this can be used without major bug fixing.

Not a bad idea. Expanding to manifest support opens the doors to _so many new_ configurations and it is hard to test them all ahead of time. Using popular projects is a good first step towards expanding the test coverage.

**Comment by marvin-hansen** [comment]
@maxrake Thank you for your effort to resolve this issue. I will ran another test soon and see how that goes. Also thank you for investigating the pull request target issue.

**Pull request closed without merging**
